version: '3.8'

services:
  web:
    build: .
    ports:
      - "8000:8000"
    environment:
      ASSEMBLYAI_API_KEY: ${ASSEMBLYAI_API_KEY}
      GENAI_API_KEY: ${GENAI_API_KEY}
    volumes:
      - .:/app