version: '3.8'

services:
  web:
    build: .
    ports:
      - "8000:8000"
    environment:
      ASSEMBLYAI_API_KEY: ${ASSEMBLYAI_API_KEY}
      GENAI_API_KEY: ${GENAI_API_KEY}
    volumes:
      - .:/app
    depends_on:
      - api

  api:
    image: python:3.12-slim
    container_name: fastapi-container
    environment:
      ASSEMBLYAI_API_KEY: ${ASSEMBLYAI_API_KEY}
      GENAI_API_KEY: ${GENAI_API_KEY}
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
